kind: pipeline
type: kubernetes
name: Build
metadata:
  namespace: runner
steps:
- name: 编译JAR
  image: gradle:6.9.3-jdk17-alpine
  commands:
  - chmod +x gradlew
  - ./gradlew jar
steps:
- name: 上传s3
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: update
    access_key: 2WrcmxFUECnFwmDP
    secret_key: 0gdHyPuD02QxXFrWzasdLsCZXJhDxo7l
    source: grasscutter-1.4.3-dev.jar
    target: /jar/
