kind: pipeline
type: docker
name: Build
clone:
  disable: true
steps:
- name: 拉取代码
  image: alpine
  environment:
    GIT:
      from_secret: GIT-HOST
  volumes:
  - name: cache
    path: /work
  commands:
  - apk add git
  - cd /work
  - git clone https://$GIT/20020314/Grasscutter.git
- name: 编译JAR文件
  image: gradle:6.9.3-jdk17-alpine
  volumes:
  - name: cache
    path: /work
  commands:
  - apk add git
  - cd /work/Grasscutter
  - chmod +x gradlew
  - ./gradlew jar
- name: 推送构建信息
  image: hongzhuangxian/pushdeer-drone-plugin
  settings:
    pushkey: PDU1TXWOAgjLH9GomOxzeNUTvjb3j3GC6DwDE
    url: https://deer.elysia.li/message/push
    type: text
volumes:
- name: cache
  temp: {}
- name: docker
  host:
    path: /var/run/docker.sock